# 워크플로우의 이름
name: Deploy 13F Scraper on Windows Laptop

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    name: Build and Deploy Job
    runs-on: self-hosted

    steps:
      # 1단계: 소스 코드 가져오기
      - name: 1. Checkout source code
        uses: actions/checkout@v4

      # 2단계: JDK 17 환경 설정
      - name: 2. Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3단계: GitHub Secret의 내용을 application.yml 파일로 생성
      - name: 3. Create application.yml from secret
        # run: PowerShell에서 실행할 명령어를 의미합니다.
        run: |
          echo "Creating application.yml..."
          # GitHub Secrets에 저장한 APPLICATION_YML 값을 가져와서 파일로 씁니다.
          echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml

      # 4단계: Gradle로 빌드 (이전의 3단계가 4단계로 밀립니다)
      - name: 4. Build with Gradle
        run: ./gradlew.bat clean bootJar

      # 5단계: 서비스 재시작하여 배포 (이전의 4단계가 5단계로 밀립니다)
      - name: 5. Deploy (Restart Windows Service)
        run: |
          echo "--> Stopping the existing service..."
          sc stop 13fDataScraper
          
          echo "--> Copying the new JAR file..."
          copy /Y "build\libs\*.jar" "C:\13f-server\app.jar"
          
          echo "--> Starting the service..."
          sc start 13fDataScraper
          
          echo "--> Deployment finished!"